# -*- coding: utf-8 -*-
"""01_cleaning.ipyn1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiEexfpGxtYN4eAI41DvzRPvYM_wjPMg
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

"""## Data Loading, Type Casting, and Advanced Cleaning."""

import pandas as pd
import numpy as np

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Explanation: This cell imports the essential libraries for the project: Pandas for data manipulation, NumPy for mathematical operations, and Matplotlib/Seaborn for data visualization.

## Load Data
"""

df = pd.read_csv("/kaggle/input/ames-housing-dataset/AmesHousing.csv")
df.head()

"""Explanation: We load the Ames Housing dataset into a DataFrame and display the first five rows to verify the contents.

## Checking Data Shape
"""

print(df.shape)

"""Explanation: This command returns a tuple representing the dimensionality of the DataFrame (total number of rows and columns).

# Inspecting Data Types
"""

df.info()

"""Explanation: We use this method to check the data types of each column and identify how many non-null values are present in the dataset.

# Fixing Data Types
"""

df['MS SubClass'] = df['MS SubClass'].astype(str)
df['Mo Sold'] = df['Mo Sold'].astype(str)

"""Explanation: We convert these two columns from integers to strings because they represent categorical classifications rather than numerical measurements.

# Identifying Missing Values
"""

print(df.isnull().sum().sort_values(ascending=False).head(10))

"""Explanation: This step calculates the total number of missing values for each column and displays the top 10 columns with the most nulls.

# Dropping High-Null Columns
"""

limit = len(df) * 0.5
df = df.dropna(thresh=limit, axis=1)

"""Explanation: We remove any columns that have more than 50% missing data, as they do not provide enough information for a reliable analysis.

# Filling Remaining Missing Values
"""

num_cols = df.select_dtypes(include=[np.number]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna("None")

"""Explanation: For the remaining columns, we fill numerical gaps with the median value and categorical gaps with the label "None" to ensure a complete dataset.

# Handling Duplicate Rows
"""

print(df.duplicated().sum())
df = df.drop_duplicates()

"""Explanation: We check for identical rows in the dataset and remove them to prevent biased results caused by redundant data.

# Spotting and Capping Outliers
"""

sns.boxplot(x=df['SalePrice'])
plt.show()

q_99 = df['SalePrice'].quantile(0.99)
df['SalePrice'] = df['SalePrice'].clip(upper=q_99)

"""Explanation: We visualize outliers using a boxplot. Then, we cap extreme values at the 99th percentile to minimize the influence of abnormally high prices.

# Reusable Cleaning Function
"""

def clean_data(raw_data):
    data = raw_data.copy()
    data['MS SubClass'] = data['MS SubClass'].astype(str)
    data['Mo Sold'] = data['Mo Sold'].astype(str)
    data = data.dropna(thresh=len(data)*0.5, axis=1)
    data = data.drop_duplicates()

    num_vars = data.select_dtypes(include=[np.number]).columns
    data[num_vars] = data[num_vars].fillna(data[num_vars].median())

    cat_vars = data.select_dtypes(include=['object']).columns
    data[cat_vars] = data[cat_vars].fillna("None")

    data['SalePrice'] = data['SalePrice'].clip(upper=data['SalePrice'].quantile(0.99))
    return data

df_final = clean_data(df)

"""Explanation: This function encapsulates all the previous cleaning steps into a single, modular block of code that can be applied to any similar dataset.

# Final Validation Checks
"""

assert df_final.isnull().sum().sum() == 0
assert (df_final['SalePrice'] > 0).all()
print(df_final.shape)

"""Explanation: These assertions perform a final check to confirm there are no missing values and that all house prices are positive, ensuring the data is ready for the next phase."""